import { test, expect } from '@playwright/test';

test('Unable to make payment Active warrant', async ({ page }) => {
  await page.goto('https://qa3customer.sonant.com/MNPaymentApplication/');
  await page.getByRole('radio', { name: 'Case Number' }).check();
  await page.getByRole('textbox', { name: 'Case Number' }).click();
  await page.getByRole('textbox', { name: 'Case Number' }).fill('69VIVB251');
  await page.getByRole('button', { name: 'Find cases by case number' }).click();
  await expect(page.locator('#referred-collection-heading')).toContainText('Active Warrant - Unable to Make Payment');
  await page.getByRole('link', { name: 'Search Again' }).click();
  await page.getByRole('radio', { name: 'Case Number' }).check();
  await page.getByRole('textbox', { name: 'Case Number' }).click();
  await page.getByRole('textbox', { name: 'Case Number' }).fill('25FA2514');
  await page.getByRole('button', { name: 'Find cases by case number' }).click();
  await page.getByRole('radio', { name: 'Testing, Respondent' }).check();
  await page.getByRole('button', { name: 'Continue with selected party' }).click();
  await expect(page.locator('#referred-collection-heading')).toContainText('Active Warrant - Unable to Make Payment');
  await page.getByRole('link', { name: 'Search Again' }).click();
  await page.getByRole('radio', { name: 'Case Number' }).check();
  await page.getByRole('textbox', { name: 'Case Number' }).click();
  await page.getByRole('textbox', { name: 'Case Number' }).fill('02FA254');
  await page.getByRole('button', { name: 'Find cases by case number' }).click();
  await page.getByRole('radio', { name: 'Petitioner, Test' }).check();
  await page.getByRole('button', { name: 'Continue with selected party' }).click();
  await expect(page.locator('#referred-collection-heading')).toContainText('Active Warrant - Unable to Make Payment');
  await page.getByRole('link', { name: 'Search Again' }).click();
  await page.getByRole('radio', { name: 'Case Number' }).check();
  await page.getByRole('textbox', { name: 'Case Number' }).click();
  await page.getByRole('textbox', { name: 'Case Number' }).fill('18FA255');
  await page.getByRole('button', { name: 'Find cases by case number' }).click();
  await page.getByRole('radio', { name: 'Testing, Respondent For' }).check();
  await page.getByRole('button', { name: 'Continue with selected party' }).click();
  await expect(page.locator('#referred-collection-heading')).toContainText('Active Warrant - Unable to Make Payment');
  await page.getByRole('link', { name: 'Search Again' }).click();
  await page.getByRole('radio', { name: 'Case Number' }).check();
  await page.getByRole('textbox', { name: 'Case Number' }).click();
  await page.getByRole('textbox', { name: 'Case Number' }).fill('70vb2551');
  await page.getByRole('button', { name: 'Find cases by case number' }).click();
  await page.goto('https://qa3customer.sonant.com/MNPaymentApplication/Case/CaseDetail?paymentPlanId=1610909524&payorId=1621404227');
  await expect(page.locator('#referred-collection-heading')).toContainText('Active Warrant - Unable to Make Payment');
  await page.getByRole('link', { name: 'Search Again' }).click();
  await page.getByRole('radio', { name: 'Case Number' }).check();
  await page.getByRole('textbox', { name: 'Case Number' }).click();
  await page.getByRole('textbox', { name: 'Case Number' }).fill('18FA256');
  await page.getByRole('button', { name: 'Find cases by case number' }).click();
  await page.getByRole('radio', { name: 'Referral, Test Collection' }).check();
  await page.getByRole('button', { name: 'Continue with selected party' }).click();
  await expect(page.locator('#referred-collection-heading')).toContainText('Active Warrant - Unable to Make Payment');
  await page.getByRole('link', { name: 'Search Again' }).click();
  await page.getByRole('radio', { name: 'Case Number' }).check();
  await page.getByRole('textbox', { name: 'Case Number' }).click();
  await page.getByRole('textbox', { name: 'Case Number' }).fill('70vb2552');
  await page.getByRole('button', { name: 'Find cases by case number' }).click();
  await page.goto('https://qa3customer.sonant.com/MNPaymentApplication/Case/CaseDetail?paymentPlanId=1610908470&payorId=1621404227');
  await expect(page.locator('#referred-collection-heading')).toContainText('Active Warrant - Unable to Make Payment');
  await page.getByRole('link', { name: 'Search Again' }).click();
  await page.getByRole('radio', { name: 'Case Number' }).check();
  await page.getByRole('textbox', { name: 'Case Number' }).click();
  await page.getByRole('textbox', { name: 'Case Number' }).fill('70vb2553');
  await page.getByRole('button', { name: 'Find cases by case number' }).click();
  await expect(page.locator('#referred-collection-heading')).toContainText('Active Warrant - Unable to Make Payment');
});